- .github/workflows/ci.yml
- README.rst
- tox.ini
- Add to the CI the Covecov
- Include the badges to README.rst
> Re-enable coverage

- .github/workflows/cd.yml
- Makefile
- README.rst
Implement a new continuous delivery for component container images.
Remove the complexity of approval (by environment) once it is an unavailable feature.
Updates the README.rst to give the link to the image usage documentation.
Closes #111
> Implements new CD

- .github/workflows/cd.yml
Fixes the release CD pipeline with GH Registry.
> fix: Release CD pipeline

- Pipfile.lock
- requirements-dev.txt
- requirements.txt
This commit update multiple dependencies and closes dependabot PRs.
> Update multiple dependencies

- .github/workflows/update-python-deps.yml
- Pipfile
- Pipfile.lock
- requirements-dev.txt
- requirements.txt
- Pinned version for starlette==0.20.4
- Add the diff for the requirement packages
- Update Python Dependencies
It is related to #183
> Pinned starlette and add verbosity to update debs

- repository_service_tuf_api/__version__.py
> Release v0.0.1a3

- docker-compose.yml
This commit add postgresql support for the new RSTUF-worker.
https://github.com/vmware/repository-service-tuf-worker/pull/145
> dev: add support for the postgresql for new worker

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- Makefile
- Pipfile.lock
- requirements-dev.txt
- requirements.txt
- fix `make requirements`
- update the API requirements and Pipfile
Closes #238
> fix make requirements and update dependencies

- repository_service_tuf_api/__version__.py
Component Interoperability Matrix
* RSTUF Worker >= v0.0.2a1
* RSTUF CLI >= v0.0.1a9
> Release v0.0.2a1

- repository_service_tuf_api/__version__.py
* Component Interoperability Matrix
- RSTUF Worker >= v0.1.0a1
> Release v0.1.0a1

- repository_service_tuf_api/__version__.py
* Component Interoperability Matrix
- RSTUF Worker >= v0.1.0a1
> Release v0.1.1a1

- .github/workflows/cd.yml
- .github/workflows/publish_container.yml
- .github/workflows/publish_docker_dev.yml
- .github/workflows/test_docker_build.yml
- Makefile
- docker-compose.yml
- docs/source/guide/Docker_README.md
Rename ghcr.io/vmware to ghcr.io/repository-service-tuf
> Rename GiHub infratructure

- repository_service_tuf_api/api/__init__.py
- tests/unit/api/test__init__.py
- tox.ini
- Fix the auth check consistence and now uses the `is_auth_enabled`.
- Add the missing unit tests for the `get_auth()`
Add more verbosity to the UT
> Fix auth check consistence and add tests

- repository_service_tuf_api/__version__.py
* Component Interoperability Matrix
- RSTUF Worker >= v0.1.0a1
> Release v0.2.0a1

- Pipfile.lock
- docs/swagger.json
- repository_service_tuf_api/__init__.py
- repository_service_tuf_api/api/config.py
- repository_service_tuf_api/common_models.py
- repository_service_tuf_api/config.py
- requirements-dev.txt
- requirements.txt
- tests/data_examples/config/update_settings.json
- tests/unit/api/test_config.py
- tests/unit/conftest.py
Add PUT /api/config endpoint to update settings.
The Worker implementation is here: https://github.com/repository-service-tuf/repository-service-tuf-worker/pull/337
Close  #350.
> Add PUT /api/config endpoint to update settings 

- repository_service_tuf_api/__version__.py
> Release v0.5.0b1

- repository_service_tuf_api/__version__.py
> Prepare v0.5.1b1 release

- repository_service_tuf_api/__version__.py
> Release v0.6.0b1

- repository_service_tuf_api/__version__.py
Prepare RSTUF API v0.7.0b1 release
> Prepare v0.7.0b1 release

- docs/swagger.json
- repository_service_tuf_api/__version__.py
> Prepare release v0.8.0b

- docs/swagger.json
- repository_service_tuf_api/bootstrap.py
- repository_service_tuf_api/config.py
- repository_service_tuf_api/metadata.py
- tests/unit/api/test_bootstrap.py
- tests/unit/api/test_config.py
- tests/unit/api/test_metadata.py
- tests/unit/api/test_targets.py
> Issue 471 - Add last_update field to PostData and PutResponse models

- docs/swagger.json
- repository_service_tuf_api/__version__.py
> Release v0.10.0b1

- .github/workflows/publish_container.yml
- .github/workflows/publish_docker_dev.yml
- .github/workflows/test_docker_build.yml
Add support to build images linux/arm64.
Related: https://github.com/repository-service-tuf/repository-service-tuf/issues/615
> feature: support container image linux/arm64

- .github/workflows/publish_container.yml
- .github/workflows/publish_docker_dev.yml
- .github/workflows/test_docker_build.yml
Includes v7 and v8 support for container arm processors
(Includes Apple M processors)
> build: Include more supported versions for arm

- docs/swagger.json
- repository_service_tuf_api/__version__.py
> Release v0.13.0b1

- repository_service_tuf_api/artifacts.py
- repository_service_tuf_api/bootstrap.py
- repository_service_tuf_api/metadata.py
- tests/unit/api/test_bootstrap.py
- tests/unit/api/test_metadata.py
- tests/unit/api/test_targets.py
This PR fixes the status code from OK (200) to NOT_FOUND (404) when the resource is not available or not in expected state when requested.
Fixes: #647
> fix: status code from OK to NOT_FOUND

- docs/swagger.json
- repository_service_tuf_api/metadata.py
Allows the bundle part for signing
This re-uses the TUFSignatures pydantic structure
> fix: sigstore distributed async signing

- docs/swagger.json
- repository_service_tuf_api/__version__.py
> release: v0.15.0b1

- docs/swagger.json
- repository_service_tuf_api/__version__.py
Release v1.0.0b2
Dependencies updates
> release: v1.0.0b2

- docs/source/devel/repository_service_tuf_api.api.rst
- docs/source/devel/repository_service_tuf_api.rst
- docs/swagger.json
- repository_service_tuf_api/__version__.py
> Release v1.0.0b3

- .github/dependabot.yml
Group dependabot updates for Github Actions
> build: group dependabot updates for GHA

- docs/swagger.json
- repository_service_tuf_api/__version__.py
Prepare the RSTUF API v1.0.0 release candidate 1
Depends on the following PRs (in the order)
> Release v1.0.0rc1

- SECURITY.md
> Adding SECURITY.md.

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/functional-tests.yml
- .github/workflows/publish_container.yml
- .github/workflows/publish_docker_dev.yml
- .github/workflows/review-approved.yml
- .github/workflows/test_docker_build.yml
- .github/workflows/update-pre-commit-hooks.yml
This PR addresses security findings from Scorecard regarding GitHub workflow token permissions. It implements the principle of least privilege by explicitly defining minimal required permissions in all workflow files.
Specific changes:
- Added explicit top-level permissions to workflows where they were missing
- Added appropriate comments documenting why each permission is needed
- Ensured all workflows follow permission best practices
By submitting this PR, you agree to follow our Code of Conduct.
```yml
permissions:
actions: read|write|none
checks: read|write|none
contents: read|write|none
deployments: read|write|none
id-token: read|write|none
issues: read|write|none
discussions: read|write|none
packages: read|write|none
pages: read|write|none
pull-requests: read|write|none …
```
> Reduce the GitHub workflow tokens' permissions

- docs/swagger.json
- repository_service_tuf_api/__version__.py
Prepare release RSTUF API v1.0.0
> release: prepare v1.0.0
