repository_service_tuf_api/bootstrap.py

The RSTUF worker is deprecating add_initial_metadata and replacing by bootstrap
This patch removes the old function and add the replaced one.
Closes #108
Signed-off-by: juniorlpa <luiz.pandradejr@gmail.com>

Migrate "add_initial_metadata" to "bootstrap"

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/publish_docker_dev.yml
.github/workflows/test_docker_build.yml

Fixes: #126 #127
Pin hashes for GitHub actions in workflow yml files.
This will allow dependabot to update our actions by using hashes
as well.
I checked the latest stable versions for each of our action dependencies and got the commit hashes.
I have done a check for security advisories for each of the actions, but haven't found any.
The versions I have used for each of the actions are as follows:
- [actions/checkout v3.1.0](https://github.com/actions/checkout/releases/tag/v3.1.0)
- [actions/setup-python v4.3.0](https://github.com/actions/setup-python/releases/tag/v4.3.0)
- [docker/setup-qemu-action v2.1.0](https://github.com/docker/setup-qemu-action/releases/tag/v2.1.0)
- [docker/setup-buildx-action v2.2.1](https://github.com/docker/setup-buildx-action/releases/tag/v2.2.1)
- …

Pin hashes for GitHub actions in workflow yml files

---

.github/workflows/cd.yml
Dockerfile

Add the release in the GitHub repository Releases.
It will give users more clear releases notes as the GHCR does not have a detailed release notes.
- Dockerfile build is missing upgrade pip and can raise error

Add release to GH repository releases

---

.github/workflows/update-python-deps.yml
Pipfile
Pipfile.lock
requirements-dev.txt
requirements.txt
tox.ini

The following PR adds a dedicated workflow for updating Python dependencies.
Details:
* Runs daily
* If another one is already opened, it doesn't create a new one, instead, it updates it.
Related to https://github.com/vmware/repository-service-tuf/issues/84
Fixes https://github.com/vmware/repository-service-tuf-api/issues/130 too
Signed-off-by: Radoslav Dimitrov <dimitrovr@vmware.com>

build: add workflow for updating python dependencies

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/other.yml
.github/ISSUE_TEMPLATE/task.yml
.github/PULL_REQUEST_TEMPLATE/pr.yml

The following PR adds templates for both issues and pull requests.
It is based on the beta feature of Github to use yml issue forms which contribute to a better user experience - ref. [github/creating-issue-forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)
Signed-off-by: Radoslav Dimitrov <dimitrovr@vmware.com>

chore: add github templates for issues and PRs

---

.github/workflows/publish_docker_dev.yml

Update the pipeline file to Limit the dev tag Docker Images only for relevant changes.
It reduces the number of builds for specific changes.
Closes #116 
Edited by @kairoaraujo 
Signed-off-by: Luiz Andrade <luiz.pandradejr@gmail.com>

Updated the pipeline file to Limit the dev tag Docker Images.

---

docs/source/guide/api/swagger.json
repository_service_tuf_api/token.py
tests/unit/api/test_token.py

The initial design for the built-in Authentication/Authorization was based on multiple users with scopes.
Users, after authentication, would receive a token with all its defined scopes.
Authentication and Authorization are not core components of RSTUF. We simplified this design to have only one user (admin), and the admin can generate Tokens with specific Scopes.
During this design change, we did not change the user fetching all scopes if the scope is empty/None.
We even want to allow the user to disable the
Authentication/Authorization layer (see
https://github.com/vmware/repository-service-tuf/issues/41) and use their  Authentication/Authorization layer.
- Add scope as required
- Add tests to avoid regression
- Hide password in the swagger try out
- Gives a clearer view of the scopes in …

Fix security issue with Tokens when empty scope

---

docs/source/guide/api/swagger.json
repository_service_tuf_api/__init__.py
repository_service_tuf_api/token.py
tests/unit/api/test_targets.py
tests/unit/api/test_tasks.py
tests/unit/api/test_token.py
tests/unit/conftest.py

Remove redundant "read:targets" scope.
Closes https://github.com/vmware/repository-service-tuf-api/issues/177

Remove redundant "read:targets" scope

---

docs/source/guide/api/swagger.json
repository_service_tuf_api/token.py
tests/unit/api/test_token.py
tests/unit/conftest.py

This fixes the possibility to generate tokens with invalid expires.
The expire is define in hours and it fixes when someone request a token with expires equal 0 or negative.
Adds also UT to avoid regression.
Closes #188

fix: generate tokens with invalid expires

---

.pre-commit-config.yaml
docs/source/guide/api/swagger.json
repository_service_tuf_api/token.py
tests/unit/api/test_token.py

Fix a bug where the generation of a token with a scope containing `read:tasks` or `delete:targets` lead to an error.
Also, disallow the generation of a token where the `scopes` field is an empty list.
I added regression tests for both changes.
Close #185 #187 

Fix the generation of tokens with specific scopes and disallow token with empty scope

---

docs/source/guide/api/swagger.json
repository_service_tuf_api/targets.py
tests/unit/api/test_targets.py

It adds to the API responses for HTTP CODE 202 (received), used by tasks, the field `last_update`.
This field helps to the requesters manage the tasks based on date time

feat: Add to the API the last_update for tasks

---

README.rst
docs/source/guide/api/swagger.json
repository_service_tuf_api/bootstrap.py

The TUF Root Metadata `consistent_snasphot: True` was not sent in the task.
The `1.root.json` in the Storage Backend was not saved with the field.
It doesn't impact the client, unless the client uses this file as the initial `root.json`.
Minor: Fix `README.rst` subtitle format.

fix: consistent snapshot field not in the task

---

docs/source/guide/Docker_README.md
repository_service_tuf_api/__init__.py

The current custom Redis configuration for the RSTUF API container doesn't work correctly.
- Fix wrong parsing for the Dynaconf configuration. The parser included the Dynaconf `envvar_prefix` `RSTUF`.
- Fix documentation
- More detail about choosing a specific port for the celery task's backend result.

fix: custom redis configuration for the container

---

Makefile

Remove some of the target folders that were deleted when "make clean" is called as those folders are not created when after a "make run-dev" call.
Connected with https://github.com/vmware/repository-service-tuf-worker/pull/158

Simplify make clean

---

.github/workflows/ci.yml
tox.ini

I noticed we run build for python3.9 when we say we support only python3.10 onwards.
That's why it seemed unnecessary that we are testing for python3.9.
On the other hand, python 3.11 was introduced back in October 2022 and we can directly add support for it.
Related to:
- https://github.com/vmware/repository-service-tuf-worker/pull/162
- https://github.com/vmware/repository-service-tuf-cli/pull/172

Remove python3.9 and add python3.11 ci build

---

.pre-commit-config.yaml
Pipfile
Pipfile.lock
repository_service_tuf_api/__init__.py
requirements-dev.txt
tox.ini

To achieve the OpenSSF Best Practices badge, we need to implement
the static code analysis tool.
This commit adds the `bandit` to the RSTUF API.

Add bandit pre commit

---

docs/source/guide/api/swagger.json
repository_service_tuf_api/targets.py
tests/data_examples/targets/payload.json
tests/unit/api/test_targets.py

Add an option which can be used for debugging to add the "task_id" of the process that adds the target into the "custom" attributes of all targets.
By default this option is enabled as it will add a small overhead, but can be quite useful for debugging in a bad scenario.
Closes https://github.com/vmware/repository-service-tuf-api/issues/57

Add an option to add task_id to target custom

---

docs/source/guide/api/swagger.json
repository_service_tuf_api/targets.py
tests/data_examples/targets/payload.json
tests/unit/api/test_targets.py

It fixes the `add_task_id_to_custom` as an optional feature.
- Change the `add_task_id_to_custom` as optional
- Change the logic case the option is missing to force as None
- Add a check if the option is True
- Increate the UT for the API feature

fix: add_task_id_to_custom feature as optional

---

docs/source/guide/api/swagger.json
repository_service_tuf_api/api/targets.py
repository_service_tuf_api/targets.py
tests/unit/api/test_targets.py

It will send to broker a task with the action `publish_targets` and return HTTP 202 and the task id (follows the same task request for add targets).
Closes #242

add API endpoint `/api/v1/targets/publish`

---

README.rst

The API listens on port 80 (http://localhost:80/), so we corrected the docs (they used to suggest
http://localhost:8000/).
Closes #233

Correct documentation for listening port of API

---

.gitignore
repository_service_tuf_api/token.py

Fix the bug in which the scope variable name is reused in a nested loop

Scope variable name reused in nested loop

---

docs/source/guide/api/swagger.json
repository_service_tuf_api/targets.py
tests/unit/api/test_targets.py
tox.ini

Add an optional field called "publish_targets" in the add/remove
targets API calls. If no value is provided or it's set to true,
publishing of targets will happen the same as now: a subtask will
be started that on completion will have published the modified targets.
If it's set to false, publishing of the targets file changes won't be
published (meaning there won't be any changes in the metadata files
as well) until specifically requested with the newly introduced
API call "api/v1/targets/publish".
This feature is was originated in Task:
https://github.com/vmware/repository-service-tuf-worker/issues/175
discussion.
Additionally, give add_task_id_to_custom a default value.
Close https://github.com/vmware/repository-service-tuf-api/issues/248

Add publish targets option

---

Pipfile
Pipfile.lock
requirements-dev.txt
requirements.txt
tests/unit/api/test_bootstrap.py
tests/unit/api/test_targets.py
tests/unit/test_app.py

It removes the pinned starlette dependency version
This pinned version was applied as a workaround for issue #183
The startelle version is updated to the latest version, which fixes a security issue https://github.com/advisories/GHSA-74m5-2c7w-9w3x
The solution requires to install the new `httpx` development dependency to support the unit tests using the FastAPI TestClient as described in this link: https://fastapi.tiangolo.com/tutorial/testing/
A workaround needs to be applied to the tests which uses `DELETE` method.

remove the pinned starlette version

---

.github/workflows/cd.yml
.github/workflows/publish_container.yml

This PR introduces a change in the `cd.yml` Workflow.
We release our components versions using the tags `v*`
The process of release has two steps:
1. Run the functional tests (FT) using the component to be released `v*` tag (from `main` branch) against the latest releases of the components.
2. If the (FT) finishes successfully, the `cd.yml` releases the new Docker Image GitHub Registry and adds it to our Releases page in Github. (Python package in case of the CLI).
If step 1 fails, the release breaks the compatibility with the current release.
The problem we are solving is how to release a new version when it breaks the compatibility.
This PR adds the workflow dispatch option for releases.
The maintainers can now go to the Actions > CD > Run Workflow, choose the `v*` tag release, and …

Flexible maintainers CD Workflow

---

.github/workflows/cd.yml

The `api_version` output was added in a previous commit and is
no longer used.

cd.yml: remove non-existing job output

---

.github/workflows/cd.yml

Add the release tag `latest` as optional.
It gives the flexibility to release or re-release new container images without adding them as a `latest` tag.

Release latest tag as optional

---

docker-compose.yml
docs/source/guide/api/swagger.json
repository_service_tuf_api/api/bootstrap.py
repository_service_tuf_api/bootstrap.py
tests/data_examples/bootstrap/payload.json
tests/unit/api/test_bootstrap.py

We no longer need to accept the information regarding keys as all roles
except root will reuse the same online key and information for it
could be provided by using the KeyVault implementations configuration
options.
Close #260

Stop accepting key info into bootstrap ceremony payload

---

app.py
docker-compose.yml
docs/source/guide/Docker_README.md
repository_service_tuf_api/api/__init__.py
repository_service_tuf_api/api/bootstrap.py
repository_service_tuf_api/api/config.py
repository_service_tuf_api/api/targets.py
repository_service_tuf_api/api/tasks.py

Introduce `RSTUF_AUTH` env variable which will allow for external
authentication providers to be plugged in.
Also, exclude all token-related API
calls when authentication is not used.
For the rest of the API calls introduce a switch that allows
to disable their authentication.
Close #282

Add a switch to remove the built-in authentication

---

docs/source/guide/Docker_README.md
docs/source/guide/api.rst

- fix the option `RSTUF_AUTH` as optional
- Add a note in the API documentation and add reference how to disable it.

fix/enhancement RSTUF API about AUTH feature

---

.github/ISSUE_TEMPLATE/config.yml
.github/workflows/cd.yml
README.rst
repository_service_tuf_api/__init__.py
setup.py

It is part of the process moving RSTUF to OpenSSF organization.

Move RSTUF to github.com/repository-service-tuf

---

repository_service_tuf_api/__init__.py

This commit fixes the environment variable used to setup a custom Redis backend result database ID, as documented in the API Guide documentation for the container configuration.
It was using by mistake the environment variable used to setup the custom Redis repository settings ID for the container.
It impacts the RSTUF deployment for custom scenarios.

fix: env variable for custom Redis result DB

---

docs/source/guide/Docker_README.md

Add the mention about the secrets standard adopted by RSTUF. RSTUF requires user to mount the secrets volume in `/run/secrets` path.

Update container docs about secrets

---

docs/source/guide/api/swagger.json
repository_service_tuf_api/common_models.py

This is synchronized with the changes in:
https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/277

Allow key custom names/tags

---

app.py
docker-compose.yml
docs/source/guide/Docker_README.md
docs/source/guide/api/swagger.json
tests/unit/test_app.py

This feature gives better flexibility to the RSTUF user to disable endpoints.
The user can disable specific endpoints and methods in a simple configuration using the `RSTUF_DISABLE_ENDPOINTS`.
It reduces the number of settings parameters (environment variables)` RSTUF_BOOTSTRAP_NODE`, and `RSTUF_TOKEN_NODE`, making the feature more flexible as we add more endpoints and methods to the RSTUF API.

More flexible disabling endpoint feature

---

docs/swagger.json
repository_service_tuf_api/__init__.py
repository_service_tuf_api/metadata.py
tests/unit/api/test_metadata.py

Metadata update: update payload and messages to follow latest decision made during the CLI implementation like removing expiration date for all roles and calling this feature `metadata update` instead of `metadata rotation`.

Metadata update: update payload and messages

---

docs/swagger.json
repository_service_tuf_api/__init__.py
repository_service_tuf_api/bootstrap.py
repository_service_tuf_api/config.py
repository_service_tuf_api/metadata.py
repository_service_tuf_api/targets.py
tests/unit/api/test_bootstrap.py
tests/unit/api/test_config.py
tests/unit/api/test_metadata.py
tests/unit/api/test_targets.py
tests/unit/tuf_repository_service_api/test__init__.py

The checks now are aligned with the Repository Settings `BOOTSTRAP` as mentioned in https://repository-service-tuf.readthedocs.io/en/stable/devel/design.html#rstuf-repository-settings-configuration
This change considers the bootstrap `pre` lock done by the RSTUF API and avoids the user can start adding/removing targets before the process finishes.
Fixes #342

Fix: protection during bootstrap process

---

tests/unit/api/test_targets.py

It fixes the deprecation tests for the target endpoint.
The error is on the main UT.
This error was caused after merging the new bootstrap checks, which fixed the tests, but those weren't in place yet.

fix: ut deprecation tests targets endpoints

---

.github/workflows/cd.yml

Fix the RSTUF Worker container image release tag.
The tag `latest` wasn't being added to the releases confusing the users running old versions.

Fix RSTUF API container image release tag

---

docs/swagger.json
repository_service_tuf_api/__init__.py
repository_service_tuf_api/api/metadata.py
repository_service_tuf_api/metadata.py
tests/data_examples/bootstrap/das-payload.json
tests/unit/api/test_metadata.py
tests/unit/conftest.py

It implements the base structure endpoints for the distributed async signing for the RSTUF.
The implementation also adds support to the distributed async sign for the bootstrap. The user can initiate the bootstrap ceremony process with the Root metadata not fully signed, and the other root ey owners can start the signing process.
It requires
- https://github.com/repository-service-tuf/repository-service-tuf-worker/issues/300
Closes #355

feat: bootstrap distributed async sign

---

Pipfile
Pipfile.lock
requirements-dev.txt
requirements.txt
tests/bdd/features/tokens/generate.feature
tests/bdd/features/tokens/login.feature
tests/bdd/tokens/__init__.py
tests/bdd/tokens/test_generate.py
tests/bdd/tokens/test_login.py
tests/conftest.py
tox.ini

The current BDD Tokens tests are part of integration tests in the RSTUF umbrella repository.
This BDD feature test doesn't belong to the integration tests once API Token authentication/authorization (auth) feature is a single component.
The BDD test is still valid once it describes very well the expected behavior.
This commit adds the test to the API and is part of the https://github.com/repository-service-tuf/repository-service-tuf/issues/41
Closes #281

Add BDD tests for Token Feature to RSTUF API

---

docs/swagger.json
repository_service_tuf_api/token.py

Fix the missing scopes in the API body validation for issuing tokens.
This PR is a quick fixing an existent bug when trying to issue a token with certain scopes.
The scopes are unlisted on the API validation.
This commit adds this missing scopes.
It is a quick fix. This is a manual update for the scope list.
The idea is to [generate a dynamic list of allowed scopes when issuing tokens](https://github.com/repository-service-tuf/repository-service-tuf-api/issues/409).
If someone has a quick fix using dynamic, feel free to replace this PR.
Fixes #408 

fix: scopes in the API body validation for token

---

docs/swagger.json
repository_service_tuf_api/targets.py
tests/data_examples/targets/payload.json
tests/unit/api/test_targets.py

Currently, we limit the hashes algorithms that are used for TargeFiles
to only "blake2b-256" which is limiting as the specification doesn't
limit to particular algorithms.
Fixes #379

Allow more hashing algorithms for TargetFiles

---

Makefile

Update docker-compose commands to use "docker compose"
This PR updates the usage of Docker Compose commands in Makefile to use the new "docker compose" syntax introduced in Docker Compose.
The new syntax offers improved consistency and ease of use.
Changes made:
Replaced occurrences of "docker-compose" with "docker compose".
Closes #392  

Update docker-compose commands by docker compose

---

docs/swagger.json
repository_service_tuf_api/__init__.py
repository_service_tuf_api/api/metadata.py
repository_service_tuf_api/metadata.py
tests/conftest.py
tests/unit/api/test_metadata.py

Add a new `DELETE /api/v1/metadata/sign` endpoint.
The purpose of this endpoint is to give a direct way for repository administrators to stop a DAS ceremony.
This DAS process can be started from both `POST /api/v1/bootstrap` and `POST /api/v1/metadata`.
This will be different than the suggested `PATCH /api/v1/metadata/sign` endpoint as this will give the opportunity to:
1. stop the DAS process immediately and do not risk other maintainers signing the metadata and passing the threshold requirement.
2. take it slow and decide what the new `bootstrap` or `metadata update` should look like
Fixes #420

feat: Add a new DELETE /api/v1/metadata/sign endpoint 

---

docs/swagger.json
repository_service_tuf_api/__init__.py
repository_service_tuf_api/api/metadata.py
repository_service_tuf_api/token.py
tests/conftest.py
tests/unit/api/test_metadata.py

Change "sign" API calls scopes more granular.
This allows for future scope `metadata` related scopes which will have a different semantics.
Also, this allows an organization to have a finer control over which of its maintainers can start or stop a DAS process through the `write:metadata_sign` and `delete:metadata_sign` scopes.
Related to those changes: https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/366
Closes #434 

Change "sign" API calls scopes more granular

---

docs/swagger.json
repository_service_tuf_api/__init__.py
repository_service_tuf_api/bootstrap.py
tests/unit/api/test_bootstrap.py

Fix the bootstrap_state checks in `post_bootstrap` and `get_bootstrap`. This makes sure that we say there is a metadata when:
- bootstrap is executed in the moment ("pre" state)
- bootstrap is in a signing process ("signing" state)
Also, fix some small things like "task_id" not sent when calling "get_bootstrap".
Added unit tests for "get_bootstrap" to make sure this mistake can be easily noticed if it happens again, for "post_bootstrap" there are tests already implemented.
Fixes #417 

Fix bootstrap_state checks in two places

---

docs/swagger.json
repository_service_tuf_api/api/metadata.py
tests/unit/api/test_metadata.py

Add a refactoring of `DELETE /api/v1/metadata/sign` with body payload to a `POST /api/v1/metadata/sign/delete`.
It makes the RSTUF API more compatible with OpenAPI and HTTP specifications, avoiding the body in the DELETE method.
Also, the current implementation is asynchronous, making adding a post more semantical as the resource is not deleted instantly.
Closes #464

Refactor DELETE /api/v1/metadata/sign

---

docs/source/guide/Docker_README.md
docs/swagger.json
repository_service_tuf_api/api/targets.py
tests/unit/api/test_targets.py

This changes the artifacts DELETE method to POST. It also updates the docker documentation by changing the targets references to artifacts.
Closes #462
Fixes #(issue)

Changes artifacts DELETE to POST

---

tests/unit/api/test_bootstrap.py
tests/unit/api/test_metadata.py
tests/unit/api/test_targets.py
tests/unit/api/test_tasks.py

A small simplification of how we define ULR strings in our tests and make
sure we do reuse them instead of defining them in each test.
Signed-off-by: Martin Vrachev <martin.vrachev@broadcom.com>

Tests: reuse URL strings

---

docs/swagger.json
repository_service_tuf_api/tasks.py
tests/unit/api/test_tasks.py

… a error, false status
This is a request coming from RubyGems maintainers that it would be better and easier for them
if they can understand that a task has failed or errored based on the returned state instead of parsing
the result and checking the status.
This will also improve all future clients.
The more detailed changes are:
The `data.state` now includes the `ERRORED` state, an error identified by RSTUF while processing a task. This error was identified and handled by RSTUF, but might require attention from the user. Details will be included in `data.result`.
The `data.result` now is a `Dict[string, Any]`. Before, it was `string` or `Dict[string, Any]`. The string was used in case of exception, which now has the same consistency.
Success tasks will follow as
Fixes #515 
By …

refactoring: update the task response data in the `/api/v1/tasks`

---

repository_service_tuf_api/common_models.py
tests/unit/api/test_bootstrap.py

This commit adds the support to unrecognized fields to the Root.
The Root.signed.unrecognized_fields can store relevant information in the TUF metadata used by TUF clients or even RSTUF Worker.
It is added to the `TUFSigned`, allowing extra fields. The unrecognized fields must to have the format `x-<vendor>-<name>`
We add a pydantic `root_validator` to verify all extra fields if they follow the required format.
Part of https://github.com/repository-service-tuf/repository-service-tuf/issues/608
This support works with RSTUF Worker which doesn't require changes.

Feature: support to unrecognized fields (Root)

---

repository_service_tuf_api/artifacts.py
repository_service_tuf_api/bootstrap.py
repository_service_tuf_api/config.py
repository_service_tuf_api/metadata.py
tests/conftest.py
tests/unit/api/test_bootstrap.py
tests/unit/api/test_config.py
tests/unit/api/test_metadata.py
tests/unit/api/test_targets.py
tests/unit/api/test_tasks.py

The specification defines `datetime` as UTC time zone:
https://theupdateframework.github.io/specification/latest/#file-formats-date-time
The python-tuf project updated all their datetime objects,  so it's time we do it now as well.
I also used the opportunity to add `MOCK_PATH` constants to simplify mocking and 
`fake_datetime` fixture, so we can reuse it.

Force UTC timezone for all datetime objects

---

docs/swagger.json
repository_service_tuf_api/api/metadata.py
repository_service_tuf_api/common_models.py
repository_service_tuf_api/config.py
repository_service_tuf_api/metadata.py
tests/unit/api/test_common_models.py
tests/unit/api/test_metadata.py

Add support for `PUT /api/v1/metadata` which will force a new metadata version
of a given set of online roles.
Fixes #399

Add support for `PUT /api/v1/metadata/online`

---

repository_service_tuf_api/metadata.py

Check first bin names instead of all.

Check first bin names instead of all

---

docs/swagger.json
repository_service_tuf_api/tasks.py

Fixes #545 
Add a new state given by celery on rare occasions
Check:
https://github.com/repository-service-tuf/repository-service-tuf-worker/blob/63c77974a402b80f618aecb9f124a6466d61149b/app.py#L118

Add a new state given by celery in rare occasions

---

.github/workflows/functional-tests.yml

Changes in API cannot affect the RSTUF Performance tested in the FT.
The performance is related to managing the TUF Metadata which is done by the RSTUF Worker
Fixes #(issue)

tests: remove FT slow from API

---

app.py
docs/source/devel/repository_service_tuf_api.api.rst
docs/source/devel/repository_service_tuf_api.rst
docs/swagger.json
repository_service_tuf_api/api/delegations.py
repository_service_tuf_api/api/metadata.py
repository_service_tuf_api/bootstrap.py
repository_service_tuf_api/common_models.py
repository_service_tuf_api/delegations.py
repository_service_tuf_api/metadata.py
repository_service_tuf_api/tasks.py
tests/data_examples/bootstrap/payload_custom_targets.json
tests/data_examples/metadata/delegation-payload.json
tests/unit/api/test_bootstrap.py
tests/unit/api/test_metadata.py

This adds a set of endpoints to enable users to manage Custom Delegations
- Add support to the POST /api/v1/bootstrap to the user define RSTUF to use Delegation Roles creating the initial Delegations
- Add POST /api/v1/delegations to add new custom delegation roles
- Add PUT /api/v1/delegations to update the custom delegation roles
- Add POST /api/v1/delegations/delete to delete  custom delegation roles
This PR requires https://github.com/repository-service-tuf/repository-service-tuf-worker/pull/593
- This PR doesn't break the compatibility with BINS, as can be checked in the [functional tests](https://github.com/repository-service-tuf/repository-service-tuf-api/actions/runs/10756070764)
TODO:
Fixes #(issue)
By submitting this PR, you agree to follow our [Code of …

feat: Custom Delegation endpoints

---

repository_service_tuf_api/metadata.py
tests/unit/api/test_metadata.py

Change what we return for GET metadata/sign, so that we return "trusted_root" only when there is pending "root" and "trusted_targets" only when "targets" is pending.
If nothing is pending we don't want to return the "trusted" roles as we do now.

Update return values for GET metadata/sign

---

repository_service_tuf_api/metadata.py
tests/unit/api/test_metadata.py

once there is a pending signing, we require to have tusted_targets
root, we keep the conditional

fix: get signing

---

Dockerfile
Makefile

The PR is about a bug fix in Makefile, where docker-compose was used in place of docker compose.
Fixes #716 

Changed docker-compose to docker compose

---

Makefile

it helps new contributors how to use the `make`
```shell
❯ make
Makefile commands:
reformat                       Reformat code with black and isort
tests                          Run all tests
precommit                      Install and run pre-commit hooks
coverage                       Run tests with coverage
build-dev                      Build the dev image
run-dev                        Run the development environment
stop                           Stop the development environment
clean                          Clean up the environment
purge                          Remove all images and containers
docs                           Build the documentation
help                           Show this help message
Environment variables:
DC: docker compose file to use (default: …
```

docs: add `make help`

---

docker-compose.yml

* Postress 15.1 to 17.5
Both have the same vulnerability scores and none of the other images have a lower vulnerability score.
* redis 4.0 to 8.0
The 4.0 image had vulnerabilities while the 8.0 doesn't have any vulnerabilities until now.

Updated Docker images
